name: jonasdemoe
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.589376
  brandStrength: 0.4355218678247184
  lightness: 0.5556492
  brandColors:
    - '#FCFDFF'
    - '#77766E'
    - '#2F3127'
    - '#E0C665'
    - '#BD9B90'
  rhythmicContrast: 0.7023609
typography_spectrum: 0.3195615
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 0.9367622
