name: jonasdemoe
favicon: null
layout_spectrum: 0.5872568802442402
typography_spectrum: 0.9456205419264734
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.43552186782471836
  lightness: 0.4540666516404599
  saturation: 0.08281188667751849
  rhythmicContrast: 0.3036536215804517
purpose: []
